export class Reports {
    active: any;
    pumpId: number;
    startDate: number;
    endDate: any[];
    vehicles: any[];
    fuelCreditBill: any[];
    cashCreditBill: any[];
    regularSales: number;
    creditSales: number;
    otherSales: number;
    loyaltySales: number;
    loyaltySalesData: any[];
    loyaltySalesSummary: any[];
    total: number;
    fuelSold;
    fuelData: any[];
    cashData: any[];
    totData: any[];
    againstAll: any[];
    AllPO: any[];
    tanks: any[];
    loyaltySalesList: any[];
    allSales: any[];
    creditAmount: number;
    advancedAmount: number;
    totalAmount: number;
    totalQty: number;
    creditLimitAllotted: number;
    creditLimitBalance: number;
    transporterId: number;
    sumAmount: number;
    sumPoints: number;
    sumQty: number;
    earnedDate: any;
    TransporterName: string;
    transporterName: string;
    name: string;
    id:any;
    sales: any[];
    transporter: any[];
    cashCreditSales: any[];
    fuelCreditSales: any[];
    totalCreditSales: any[];
    products: any[];
    totalCSAmount: number;
    totalCSBillAmount: number;
    totalPaymentAmount: number;
    newDrivers: number;
    totalDriver: number;
    visitedDriversCount: number;
    totalRegularAmount: number;
    totalLoyaltyAmount: number;
    totalCreditAmount: number;
    empCount:number;
    vehicleCount:number;
    driverCount:number;
    mgrCount:number;
    reqCount:number;
    pumpCount:number;
    transCount:number;
    transporterFuelBill:any;
    transporterCashBill:any;
    DriverData;
    AllCS: any[];
    AllLS: any[];
    allCashDue: any[];
    allFuelDue: any[];
    allTotalDue: any[];
    constructor() {
    }
}